name: PS4 HEN Payload

on: [push, pull_request]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: clone
      uses: actions/checkout@main

    - name: Set execute permission for build.sh
      run: |
        chmod +x clean.sh
        chmod +x build.sh

    - name: Build
      run: |
        ./clean.sh
        ./build.sh

    - name: release for branch 950
      if: github.event_name == 'push' && github.ref == 'refs/heads/950'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release create 950-1.0${{ GITHUB.RUN_NUMBER }} ps4-hen-950-vtx.bin --target ${{ GITHUB.SHA }} -t 950-1.0${{ GITHUB.RUN_NUMBER }}
